name: flutterfire_commons

repository: https://github.com/KosukeSaigusa/flutterfire-commons

packages:
  - packages/**
  - '*'

scripts:
  clean:
    run: melos exec -- "flutter clean"

  pub:get:
    run: melos exec -- "flutter pub get"

  clean:pub:get:
    run: melos exec -- "flutter clean && flutter pub get"
