name: listen_with_riverpod
description: A sample of Riverpod listen
version: 0.0.1

environment:
  sdk: '>=2.17.1 <3.0.0'
  flutter: '>=3.0.1'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
