name: example_listen_with_riverpod
description: A sample of Riverpod listen
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.17.1 <3.0.0'
  flutter: '>=3.0.1'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0-dev.9
  flutter_state_notifier: ^0.7.1
  freezed_annotation: ^2.0.3

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1

flutter:
  uses-material-design: true
