name: example_dark_theme_sample
description: A new Flutter project.
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.10.4"

dependencies:
  cloud_firestore:
  dark_theme_sample:
    path: ../
  firebase_core:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
