targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/providers/**/*state.dart
            - lib/models/**/*.dart
      json_serializable:
        options:
          checked: true
          field_rename: snake
